site_name: elmah.io Documentation
site_description: Documentation on how to install and use elmah.io.
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
site_favicon: favicon.ico
google_analytics: ['UA-42575460-4', 'docs.elmah.io']
pages: 
- Docs:
    - Home: index.md
- Installation:
    - Logging from ELMAH: logging-to-elmah-io-from-elmah.md
    - Logging from Web API: logging-to-elmah-io-from-web-api.md
    - Logging from Serilog: logging-to-elmah-io-from-serilog.md
    - Logging from log4net: logging-to-elmah-io-from-log4net.md
    - Logging from NLog: logging-to-elmah-io-from-nlog.md
    - Logging from Nancy: logging-to-elmah-io-from-nancy.md
    - Logging from ServiceStack: logging-to-elmah-io-from-servicestack.md
    - Logging from BlogEngine.NET: logging-to-elmah-io-from-blogengine-net.md
    - Logging from Umbraco: logging-to-elmah-io-from-umbraco.md
    - Logging from JSNLog: logging-to-elmah-io-from-jsnlog.md
    - Logging from Console: logging-to-elmah-io-from-console-application.md
    - Logging from Sitefinity: logging-to-elmah-io-from-sitefinity.md
    - Configure elmah.io manually: configure-elmah-io-manually.md
    - Configure elmah.io from code: configure-elmah-io-from-code.md
- Integrations:
    - Slack: integrate-elmah-io-with-slack.md
    - HipChat: integrate-elmah-io-with-hipchat.md
    - Zapier: integrate-elmah-io-with-zapier.md
- Help:
    - Logging custom data: logging-custom-data.md
    - Logging errors programmatically: logging-errors-programmatically.md
    - Logging through a HTTP proxy: logging-through-a-http-proxy.md
    - Logging to multiple logs: logging-to-multiple-elmah-logs.md
    - Remove sensitive form data: remove-sensitive-form-data.md
    - Use Extended User Details without Email as Id: use-extended-user-details-without-email-as-id.md
    - Use multiple logs for different environments: use-multiple-logs-for-different-environments.md
    - Using the elmah.io extension for Visual Studio: using-the-elmah-io-extension-for-visual-studio.md
    - Handle elmah.io downtime: handle-elmah-io-downtime.md