site_name: elmah.io Documentation
site_description: Documentation on how to install and use elmah.io.
theme_dir: "mkdocs_bootstrap"
include_next_prev: false
site_favicon: favicon.ico
pages: 
- Docs:
    - Home: index.md
- Installation:
    - Logging from ELMAH: logging-to-elmah-io-from-elmah.md
    - Logging from ASP.NET MVC: logging-to-elmah-io-from-aspnet-mvc.md
    - Logging from Web API: logging-to-elmah-io-from-web-api.md
    - Logging from ASP.NET Core: logging-to-elmah-io-from-aspnet-core.md
    - Logging from Serilog: logging-to-elmah-io-from-serilog.md
    - Logging from log4net: logging-to-elmah-io-from-log4net.md
    - Logging from NLog: logging-to-elmah-io-from-nlog.md
    - Logging from Nancy: logging-to-elmah-io-from-nancy.md
    - Logging from ServiceStack: logging-to-elmah-io-from-servicestack.md
    - Logging from BlogEngine.NET: logging-to-elmah-io-from-blogengine-net.md
    - Logging from Umbraco: logging-to-elmah-io-from-umbraco.md
    - Logging from JSNLog: logging-to-elmah-io-from-jsnlog.md
    - Logging from Console: logging-to-elmah-io-from-console-application.md
    - Logging from Sitefinity: logging-to-elmah-io-from-sitefinity.md
    - Logging from Express: logging-to-elmah-io-from-express.md
    - Configure elmah.io manually: configure-elmah-io-manually.md
    - Configure elmah.io from code: configure-elmah-io-from-code.md
    - Logging through a HTTP proxy: logging-through-a-http-proxy.md
- Apps:
    - Slack: elmah-io-apps-slack.md
    - HipChat: elmah-io-apps-hipchat.md
    - GitHub: elmah-io-apps-github.md
    - BotBuster: elmah-io-apps-botbuster.md
    - Creating apps for elmah.io: creating-apps-for-elmah-io.md
- Help:
    - Logging custom data: logging-custom-data.md
    - Logging errors programmatically: logging-errors-programmatically.md
    - Logging to multiple logs: logging-to-multiple-elmah-logs.md
    - Remove sensitive form data: remove-sensitive-form-data.md
    - Handle elmah.io downtime: handle-elmah-io-downtime.md
    - Use Extended User Details without Email as Id: use-extended-user-details-without-email-as-id.md
    - Use multiple logs for different environments: use-multiple-logs-for-different-environments.md
    - Adding version information: adding-version-information.md
    - ELMAH and custom errors: elmah-and-custom-errors.md
    - Using the elmah.io extension for Visual Studio: using-the-elmah-io-extension-for-visual-studio.md
    - Using the REST API: using-the-rest-api.md
    - Integrating with Slack manually: integrate-elmah-io-with-slack.md
    - Integrating with HipChat manually: integrate-elmah-io-with-hipchat.md
    - Integrating with Zapier: integrate-elmah-io-with-zapier.md 